name: NIDE
description: Seu app de beneficios!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  file_picker: ^8.1.7
  typed_data: ^1.3.2
  html: ^0.15.4
  flutter_snake_navigationbar: ^0.6.1
  url_launcher: ^6.0.20
  path_provider: ^2.1.5
  firebase_core: ^3.4.1
  flutter_svg: ^2.0.10+1
  # qr_code_scanner: ^1.0.1
  flutter_custom_tabs: ^2.1.0
  # google_ml_vision: ^0.0.8
  camera: ^0.10.0+1  # Adjust to the latest version compatible with your Flutter SDK
  uuid: ^4.5.1
  intl: ^0.18.0  # Ou a versão mais recente disponível
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  permission_handler: ^11.3.1
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  qr_code_scanner_plus: ^2.0.7
  video_player: ^2.9.2
  youtube_player_iframe: ^4.0.4
  google_maps_flutter: ^2.1.1
  geolocator: ^9.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  flutter_credit_card: ^4.1.0
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.4.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  universal_io: ^2.2.2






  





# dart run flutter_native_splash:create



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/illustrator/illustrator1.png
    - assets/images/illustrator/illustrator2.png
    - assets/images/logo/image.png
    - assets/images/logo/white.png
    - assets/images/logo/blue.png



    - .env


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf

